# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonMua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField()),
                ('GiaMua', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatHang',
            fields=[
                ('MaHang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenHang', models.CharField(max_length=30, unique=True)),
                ('DonViTinh', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='donmua',
            name='MaHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MatHang'),
        ),
    ]
