# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donmua',
            name='MaHang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.MatHang'),
        ),
    ]
