# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170221_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donmua',
            name='GiaMua',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donmua',
            name='SoLuong',
            field=models.IntegerField(default=0),
        ),
    ]
