# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170221_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(default=0)),
                ('GiaMua', models.IntegerField(default=0)),
                ('MaHang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.MatHang')),
            ],
        ),
    ]
