# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170221_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=100)),
                ('DienThoai', models.CharField(max_length=15)),
            ],
        ),
    ]
