# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDBan',
            fields=[
                ('MaHDBan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NgayBan', models.DateTimeField()),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.KhachHang')),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.NhanVien')),
            ],
        ),
    ]
