# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hdban'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hang',
        ),
        migrations.RemoveField(
            model_name='hdban',
            name='MaKhachHang',
        ),
        migrations.RemoveField(
            model_name='hdban',
            name='MaNhanVien',
        ),
        migrations.DeleteModel(
            name='HDBan',
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.DeleteModel(
            name='NhanVien',
        ),
    ]
