# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170314_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donban',
            name='MaHang',
        ),
        migrations.RemoveField(
            model_name='donmua',
            name='MaHang',
        ),
        migrations.DeleteModel(
            name='DonBan',
        ),
        migrations.DeleteModel(
            name='DonMua',
        ),
        migrations.DeleteModel(
            name='MatHang',
        ),
    ]
