# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hang',
            fields=[
                ('MaHang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenHang', models.CharField(max_length=50, unique=True)),
                ('SoLuong', models.IntegerField()),
                ('GiaMuaVao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('GiaBanRa', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='HDBan',
            fields=[
                ('MaHDBan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NgayBan', models.DateTimeField()),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=100)),
                ('DienThoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenNhanVien', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=100)),
                ('DienThoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='hdban',
            name='MaKhachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jDream.KhachHang'),
        ),
        migrations.AddField(
            model_name='hdban',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jDream.NhanVien'),
        ),
    ]
