# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdban',
            name='TongTien',
        ),
    ]
