# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0002_remove_hdban_tongtien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdban',
            name='MaKhachHang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jDream.KhachHang'),
        ),
        migrations.AlterField(
            model_name='hdban',
            name='MaNhanVien',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jDream.NhanVien'),
        ),
    ]
