# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0005_auto_20170319_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='hang',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
