# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jDream.models


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0006_hang_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHDBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField()),
                ('ThanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaHDBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jDream.HDBan')),
            ],
        ),
        migrations.AlterField(
            model_name='hang',
            name='image',
            field=models.ImageField(blank=True, upload_to=jDream.models.directory_path),
        ),
        migrations.AddField(
            model_name='chitiethdban',
            name='MaHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jDream.Hang'),
        ),
    ]
