# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0008_auto_20170327_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitiethdban',
            name='MaHang',
        ),
        migrations.AddField(
            model_name='chitiethdban',
            name='MaHang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jDream.Hang'),
            preserve_default=False,
        ),
    ]
