# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0009_auto_20170327_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitiethdban',
            name='ThanhTien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
