# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jDream', '0010_auto_20170327_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitiethdban',
            name='ThanhTien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
